CREATE TABLE ACCOUNT(
	CUSTOMER_ID INT(11) NOT NULL AUTO_INCREMENT,
	OUTSTANDING_BALANCE DOUBLE(11) NOT NULL,
	ADDRESS VARCHAR(100) NOT NULL,
	PRIMARY KEY(CUSTOMER_ID)
);

CREATE TABLE ITEMS(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	IMAGE VARCHAR(500),
	COST INT(11) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE STOCK(
	ID INT(11) NOT NULL,
	QUANTITY INT(11) NOT NULL,
	PRIMARY KEY(ID)
);


